#!/bin/bash

unamestr=`uname`
version="2.0"
pwd=`pwd`
dataFolder="$pwd/$version/data"
toolsFolder="$pwd/$version/tools"
PangeaRepo="http://www.smalltalkhub.com/mc/SCG/Pangea/main"
defaultExtractor="verveinej11"
CORES=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || sysctl -n hw.ncpu)

# useful function
echoerr() { echo "$@" 1>&2; }

TMP_OS=`uname | tr "[:upper:]" "[:lower:]"`
if [[ "{$TMP_OS}" = *darwin* ]]; then
    OS="mac";
elif [[ "{$TMP_OS}" = *linux* ]]; then
    OS="linux";
elif [[ "{$TMP_OS}" = *win* ]]; then
    OS="win";
elif [[ "{$TMP_OS}" = *mingw* ]]; then
    OS="win";
else
    echo "Unsupported OS";
    exit 1;
fi


if [[ "$OS" == 'linux' ]]; 
then
   VM="$toolsFolder/vm/pharo-linux/pharo  -vm-display-null "
   VM_UI="$toolsFolder/vm/pharo-linux/pharo  "
elif [[ "$OS" == 'mac' ]]; 
then
   VM="$toolsFolder/vm/pharo-mac/Pharo.app/Contents/MacOS/Pharo --headless --memory 1536m"
   VM_UI="$toolsFolder/vm/pharo-mac/Pharo.app/Contents/MacOS/Pharo --memory 1536m"
fi




getDefaultExtractor() {
	corpus=$1
	if [[ "$corpus" == 'Squeaksource-100' ]];
	then
		echo "moose"
	else
		echo  "verveinej11"
	fi
}


#####################################################################################################################
## pangea get #######################################################################################################

#########################
## get gata
makeRootFolderStructure() {
	mkdir -p "$pwd/$version"
	mkdir -p "$pwd/$version/examples"
	mkdir -p "$pwd/$version/data"
	mkdir -p "$pwd/$version/tools"
}

makeCorpusFolderStructure() {
	mkdir -p "$dataFolder/$1"       
	mkdir -p "$dataFolder/$1/sources"    
	mkdir -p "$dataFolder/$1/models"	
}

#$1 corpus name
#$2 extractor name
makeModelFolderStructure() {
	mkdir -p "$dataFolder/$1/models/$2"
	mkdir -p "$dataFolder/$1/models/$2/extractor"
	mkdir -p "$dataFolder/$1/models/$2/mse"
	mkdir -p "$dataFolder/$1/models/$2/images"
}

downloadCorpusSources(){
	corpusURI='http://scg.unibe.ch/pangea/'$version'/data/'$1'/sources/'
	download=1
	i=1
	while [  $download -eq 1 ]; do
		targetURI=$corpusURI'pt'$i'.tar'
		exists=`curl -s --head $targetURI | head -n 1 | grep "HTTP/1.[01] [23].."`
		if [ -z "$exists" ]; then
			download=0
		else	
			echo "== download $targetURI"
			curl -o "$dataFolder/$1/sources/pt$i.tar"  $targetURI
			i=$[i+1]
		fi
	done
}

downloadExtractor() { ## downloadExtractor "QC-20120401r" "verveinej11"
	QCname=$1
	ExtrName=$2
	
	extractorURI="http://scg.unibe.ch/pangea/$version/data/$QCname/models/$ExtrName/extractor"
	curl -o "$dataFolder/$QCname/models/$ExtrName/extractor/extractor.zip" "$extractorURI/extractor.zip"
	curl -o "$dataFolder/$QCname/models/$ExtrName/extractor/extract.sh" "$extractorURI/extract.sh"
	 
	unzip "$dataFolder/$QCname/models/$ExtrName/extractor/extractor.zip" -d "$dataFolder/$QCname/models/$ExtrName/extractor"
	rm "$dataFolder/$QCname/models/$ExtrName/extractor/extractor.zip"
}

downloadCorpusModels() { ## downloadCorpusModels "QC-20120401r"
	QCname=$1

	corporaURI="http://scg.unibe.ch/pangea/$version/data/$QCname/models/contents.txt"
	curl -o "$dataFolder/$QCname/models/contents.txt" $corporaURI

	
	while read model; do
  		echo "== download extractor $model"
  		remoteTar="http://scg.unibe.ch/pangea/$version/data/$QCname/models/$model/mse/mse.tar"
  		localTar="$dataFolder/$QCname/models/$model/mse/mse.tar"
  		localMSEFolder="$dataFolder/$QCname/models/$model/mse/"
		
		makeModelFolderStructure $QCname $model
		downloadExtractor $QCname $model
		curl -o $localTar $remoteTar
		tar xvf $localTar -C $localMSEFolder
		
		echo "removing the mse.tar..."
		rm "$dataFolder/$QCname/models/$model/mse/mse.tar"
	done < "$dataFolder/$QCname/models/contents.txt"
	
}

unpackCorpusSource() {
	QCname=$1
	
	echo "== uncompress $QCname"
	for f in $(find "$dataFolder/$QCname/sources/" -name 'pt*.tar'); do
		tar xvf $f -C "$dataFolder/$QCname/sources/"
	done
	echo "removing the source archives..."
	rm "$dataFolder/$QCname/sources/pt*.tar"
}

unpackQualitasCorpus(){ ## unpackQualitasCorpus "QC-20120401r"
	QCname=$1
	installFile="$dataFolder/$QCname/sources/$QCname/bin/install.pl"
	echo "== uncompress"
	echo "$installFile"
	# -------- unpack qualitas corpus 
	if [ -e $installFile ]; then
		echo "== install Qualitas Corpus"
		chmod +x "$installFile"
		echo "$installFile"
		echo "y" | $installFile
	fi	
}


downloadCorpus() {
	QCname=$1
	
	makeCorpusFolderStructure $QCname
	downloadCorpusSources $QCname
	downloadCorpusModels $QCname
	unpackCorpusSource $QCname
	unpackQualitasCorpus $QCname
}

downloadOnlyMSE() {
	QCname=$1
	
	makeCorpusFolderStructure $QCname
	downloadCorpusModels $QCname
}


downloadAllCorpora(){
	corporaURI='http://scg.unibe.ch/pangea/'$version'/data/content.txt'
	curl -o "$dataFolder/content.txt" $corporaURI
	
	while read corpus; do
  		echo "== download $corpus"
		downloadCorpus $corpus

	done < "$dataFolder/content.txt"
}

downloadAndUnpackTools() {
	toolsURI='http://scg.unibe.ch/pangea/'$version'/tools'
	curl -o "$toolsFolder/image.tar" "$toolsURI/image.tar"
	curl -o "$toolsFolder/vm.tar" "$toolsURI/vm.tar"

	tar xvf "$toolsFolder/image.tar" -C "$toolsFolder/$1"
	tar xvf "$toolsFolder/vm.tar" -C "$toolsFolder/$1"

	rm "$toolsFolder/image.tar"
	rm "$toolsFolder/vm.tar"
}


unpackCorpus(){
	
	echo "== uncompress"
	for f in $(find . -name 'pt*.tar'); do
		tar xvf $f
	done
	tar xvf 'MSE.tar'
	tar xvf 'metadata.tar'
	
	# -------- unpack qualitas corpus 
	prefix=${1:6:2}
	if [ "$prefix" == 'QC' ]; then
		echo "== install Qualitas Corpus"
		version=${1:9}
		chmod +x 'QualitasCorpus-'$version'/bin/install.pl' 
		'./QualitasCorpus-'$version'/bin/install.pl'
		mv 'QualitasCorpus-'$version 'QC-'$version
	fi	

	# -------- remove downloaded archives
	rm *.tar	
}

downloadAndUnpackImagesForCorpus() {
	QCname=$1
	ExtrName=$2

	imagesFolder="$dataFolder/$QCname/models/$ExtrName/images"
	imagesURI="http://scg.unibe.ch/pangea/$version/data/$QCname/models/$ExtrName/images/images.tar"

	curl -o "$imagesFolder/images.tar" "$imagesURI"
	tar xvf "$imagesFolder/images.tar" -C "$imagesFolder"

	# rm "$toolsFolder/image.tar"
	# rm "$toolsFolder/vm.tar"

}

downloadAndUnpackImagesForAllCorpora(){
	while read corpus; do
  		echo "== download images for $corpus"
		downloadAndUnpackImagesForCorpus $corpus

	done < "$dataFolder/content.txt"
}


#####################################################################################################################
## pangea make image #######################################################################################################

makeImages(){  ## makeImages "QC-20120401r" "verveinej11"

	QCname=$1
	ExtrName=$2
	mseFolder="$dataFolder/$QCname/models/$ExtrName/mse"
	mseFiles=`find $mseFolder -name "*.mse"`

	cp "$toolsFolder/image/Moose.image" "$toolsFolder/image/MooseCurrent.image"
	cp "$toolsFolder/image/Moose.changes" "$toolsFolder/image/MooseCurrent.changes"
	
	moose="$toolsFolder/image/MooseCurrent.image"
	
	$VM $moose config $PangeaRepo ConfigurationOfPangea --install=development
	
	
	for sourcePath in $mseFiles; do
		mseFileWithoutExtension=`basename $sourcePath .mse`
		mseFileName=$mseFileName".mse"
		
		imgDest="$dataFolder/$QCname/models/$ExtrName/images"
		
		absoluteScrFolder=$dataFolder/$QCname/sources/$QCname/Systems

		$VM $moose PangeaLoadMSE --source=$absoluteScrFolder --mse=$sourcePath --name=$mseFileWithoutExtension	
		mv "$toolsFolder/image/$mseFileWithoutExtension.image" $imgDest
		mv "$toolsFolder/image/$mseFileWithoutExtension.changes" $imgDest
		
	done	
	
}

#####################################################################################################################
## pangea make mse #######################################################################################################

makeMSE(){  ## makeMSE  "QC-20120401r" "verveinej11" 
	QCname=$1 
	ExtrName=$2
	
	serachFolder="$dataFolder/$QCname/sources"
	srcFolders=`find $serachFolder -type d -maxdepth 5  -path "*/src" | grep -v /src/ | grep -v /$QCname/docs/`
	
	
	for srcFolder in $srcFolders; do		
		mseFileName=`echo $srcFolder | awk -F"/" '{print $(NF-1)}' `
		mseFilePath="$dataFolder/$QCname/models/$ExtrName/mse/$mseFileName.mse"
		
		srcRelativeFolder=`echo $srcFolder | awk -F"/" '{print $(NF-2)"/"$(NF-1)}'`
		runFolder="$dataFolder/$QCname/sources/$QCname/Systems"
				
		chmod +x "$dataFolder/$QCname/models/$ExtrName/extractor/extract.sh"
		(cd $dataFolder/$QCname/models/$ExtrName/extractor && $dataFolder/$QCname/models/$ExtrName/extractor/extract.sh "$srcRelativeFolder/src" $mseFilePath $runFolder)
			
	done	
}

#####################################################################################################################
## pangea run ######################################################################################################

runScript() {
	QCname=$1 
	ExtrName=$2
	Script=$3

	#echo $VM
	echoerr `date`
	imagesFolder="$dataFolder/$QCname/models/$ExtrName/images"

	for imageFile in `find $imagesFolder |  grep "image$" `; do
			echoerr "--" `(basename "$imageFile")`
			# echo $VM $imageFile st $pwd/$Script 2>/dev/null
			$VM $imageFile st $pwd/$Script 2>/dev/null
	done
	echoerr `date`
}


runParallelScript() {
	QCname=$1 
	ExtrName=$2
	Script=$3
	ScriptName=`(basename "$Script")`
	mkdir results/$ScriptName
	

	#echo $VM
	echoerr `date`
	imagesFolder="$dataFolder/$QCname/models/$ExtrName/images"
	
	for imageFile in `find $imagesFolder |  grep "image$" `; do
			systemName=`(basename "$imageFile")`
			# echoerr "--" $systemName
			# echo $VM $imageFile st $pwd/$Script 2>/dev/null
			$VM $imageFile st $pwd/$Script > results/$ScriptName/$systemName.output 2>/dev/null && echo "Done" $systemName &
			while [ $(jobs | wc -l) -ge $CORES ] ; do sleep 0.01 ; done
	done
	wait
	echoerr `date`
}

listCorpora() {
	corporaURI='http://scg.unibe.ch/pangea/2.0/data/content.txt'
	echo "Available: " 
	echo " " `curl -s $corporaURI`

	echo "Installed: "
	listInstalledCorpora
}

listInstalledCorpora(){
	if ! [ -d 2.0 ]
	then
		echo " none"
	else
		echo " " `(cd 2.0/data/ && ls -d */ | sed s/\\\///g)`
	fi
}

helpSpecifyCorpus(){
	if ! [ -d 2.0 ]
	then
		echo " error"
	else
		echo " please choose a corpus: " `(cd 2.0/data/ && ls -d */ | sed s/\\\///g)`
	fi
}

#####################################################################################################################
## pangea make ######################################################################################################

if [ $# -eq 0 ]
  then
   	echo "---=== Usage ===---"
    echo "       pangea get <src|mse|imgs> [-c QCr] "
    echo "       pangea make <all|mse|imgs> [-c QCr] [-e /path/to/extractor | name] [-m /path/to/mooseImage] "
    echo "       pangea clean <all|mse|imgs> [-c QCr]"
    echo "       pangea [run|parallel] script [-c QCr] <script-name.st>"
    echo "       pangea corpora"
    echo "       pangea images [-c QCr]"
    echo "       pangea experiment [-c QCr] [system name]"
    echo ""
    echo "---=== Corpora ===---"
    listCorpora
    exit
fi



case "$1" in

corpora)
	listCorpora
	;;
get)
	makeRootFolderStructure
	downloadAndUnpackTools

    case "$2" in
    	src)
			downloadCorpus $4			
		;;        
        mse) 
		if [ $# == 4 ]; 
		then
			if [ "$3" == "-c" ];
			then
				echo "==getting the mse files for $4"					
				downloadOnlyMSE $4					
			else
				helpSpecifyCorpus
				exit;
            	fi
		else			
			downloadAllCorpora			
		fi
    	;;    	
    	imgs)
		if [ $# == 4 ]; 
		then
			if [ "$3" == "-c" ];
			then
				extractor=`getDefaultExtractor $4`			
				downloadAndUnpackImagesForCorpus $4 $extractor
			else
				helpSpecifyCorpus
				exit;
            	fi
		else
			downloadAndUnpackImagesForAllCorpora
		fi

    	;;
    esac
;;
make)
	case "$2" in
		mse)
		echo "Start MSE creation"
		if [ $# == 4 ]; 
		then
			if [ "$3" == "-c" ];
			then
				makeMSE $4 "verveinej11"
			else
				helpSpecifyCorpus
				exit;
            	fi
		else
			echo "a";
		fi
		;;

		imgs)
		echo "Start image creation"
		if [ "$3" == "-c" ];
		then	
			if [ $# == 4 ]; 
			then
				extractor=`getDefaultExtractor $4`
				makeImages $4 $extractor
			fi
		else
			helpSpecifyCorpus
			exit;
        fi
		;;
	esac
;;
clean)
;;
images)
	case "$2" in
		"-c")
		if [ $# == 3 ];
			then
			extractor=`getDefaultExtractor $4`
			ls $dataFolder/$3/models/$extractor/images/*.image
		else
			echo "expecting corpus name"
		fi
		;;		
	*) 
		helpSpecifyCorpus	
	esac
;;
experiment)
	case "$2" in
			"-c")
			if [ $# == 4 ];
				then
				extractor=`getDefaultExtractor $3`
				first=`find $dataFolder/$3/models/$extractor/images -iname $4*.image | head -1`	
				$VM_UI $first &			
			else
				extractor=`getDefaultExtractor $3`
				first=`find $dataFolder/$3/models/$extractor/images -iname *.image | head -1`
				$VM_UI $first &
			fi	
			;;		
		*) 
			helpSpecifyCorpus
	esac
;;

edit)
	case "$2" in
		"-c")
		if [ $# == 4 ];
			then
			$EDITOR $dataFolder/$3/sources $4
		else
			echo "error"
		fi	
	esac
;;
run)
	case "$2" in
		script)
		# echo "Run script"
		if [ $# == 5 ]; 
		then
			if [ "$3" == "-c" ];
			then
				# echo "running script..."
				extractor=`getDefaultExtractor $4`
				runScript $4 $extractor $5
			else
				echo "wrong arguments"
				exit;
            	fi
		else
			echo "a";
		fi
		;;

		parallel)
		echo "Running the script with MASSIVE parallelization..."
		if [ $# == 5 ]; 
		then
			if [ "$3" == "-c" ];
			then
				# echo "running script..."
				extractor=`getDefaultExtractor $4`
				runParallelScript $4 $extractor $5
			else
				echo "wrong arguments"
				exit;
            	fi
		else
			echo "a";
		fi
		;;		
	esac
;;
*) echo "Signal number $1 is not processed"
;;
esac

